import pickle
class variable():
    def __init__(self,value):
        self.value=value
class pokemon:
    def __init__(self,name,hp,move1,move2,hpmax,cat,multi,fight):
        self.name=name
        self.hp=hp
        self.move1=move1
        self.move2=move2
        self.hpmax=hpmax
        self.cat=cat
        self.multi=multi
        self.fight=fight
pikachu=pokemon('Pikachu',100,'Thunder Shock','Electro Ball',100,'Electric',1,0)
raichu=pokemon('Raichu',150,'Thunder Shock','Electro Ball',150,'Electric',2,0)
squirtle=pokemon('Squirtle',100,'Psybeam','Hydro Pump',100,'Water',1,0)
wartortle=pokemon('Wartortle',150,'Psybeam','Hydro Pump',150,'Water',2,0)
blastoise=pokemon('Blastoise',200,'Psybeam','Hydro Pump',200,'Water',3,0)
charmender=pokemon('Charmender',100,'Ember','Flame Thrower',100,'Fire',1,0)
charmeleon=pokemon('Charmeleon',150,'Ember','Flame Thrower',150,'Fire',2,0)
charizard=pokemon('Charizard',200,'Ember','Flame Thrower',200,'Fire',3,0)
bulbasaur=pokemon('Bulbasaur',100,'Razor Leaf','Vine Whip',100,'Grass',1,0)
ivysaur=pokemon('Ivysaur',150,'Razor Leaf','Vine Whip',150,'Grass',2,0)
venasaur=pokemon('Venasaur',200,'Razor Leaf','Vine Whip',200,'Grass',3,0)
pidgey=pokemon('Pidgey',100,'Gust','Steel Wing',100,'Air',1,0)
pidgeotto=pokemon('Pidgeotto',150,'Gust','Steel Wing',150,'Air',2,0)
pidgeot=pokemon('Pidgeot',200,'Gust','Steel Wing',200,'Air',3,0)
gastly=pokemon('Gastly',100,'Sucker Pumch','Shadow Ball',100,'Ghost',1,0)
haunter=pokemon('Haunter',150,'Sucker Pumch','Shadow Ball',150,'Ghost',2,0)
gengar=pokemon('Gengar',200,'Sucker Pumch','Shadow Ball',200,'Ghost',3,0)
abra=pokemon('Abra',100,'Confusion','Barrier',100,'Psychic',1,0)
kadabra=pokemon('Kadabra',150,'Confusion','Barrier',150,'Psychic',2,0)
alakazam=pokemon('Alakazam',200,'Confusion','Barrier',200,'Psychic',3,0)
machop=pokemon('Machop',100,'Counter','Double Kick',100,'Fighting',1,0)
machoke=pokemon('Machoke',150,'Counter','Double Kick',150,'Fighting',2,0)
machamp=pokemon('Machamp',200,'Counter','Double Kick',200,'Fighting',3,0)
geodude=pokemon('Geodude',100,'Quick Attack','Rock Throw',100,'Rock',1,0)
gravelar=pokemon('Gravelar',150,'Quick Attack','Rock Throw',150,'Rock',2,0)
golem=pokemon('Golem',200,'Quick Attack','Rock Throw',200,'Rock',3,0)
magmar=pokemon('Magmar',100,'Ember','Flame Thrower',100,'Fire',2,0)
flareon=pokemon('Flareon',100,'Ember','Flame Thrower',100,'Fire',2,0)
polywrath=pokemon('Polywrath',100,'Psybeam','Hydro Pump',100,'Water',2,0)
golduck=pokemon('Golduck',100,'Psybeam','Hydro Pump',100,'Water',2,0)
taurus=pokemon('Taurus',100,'Counter','Double Kick',100,'Grass',2,0)
onix=pokemon('Onix',100,'Quick Attack','Rock Throw',100,'Rock',2,0)
fearow=pokemon('Fearow',100,'Gust','Steel Wing',100,'Air',2,0)
farfetch=pokemon('Farfetch',100,'Gust','Steel Wing',100,'Air',2,0)
dragonite=pokemon('Dragonite',150,'Flame Thrower','Hyper Beam',100,'Normal',2,0)
zapdos=pokemon('Zapdos',150,'Thunder Shock','Electro Ball',150,'Electric',2,0)
vaporeon=pokemon('Vaporeon',150,'Psybeam','Hydro Pump',150,'Water',2,0)
pokeballs=variable(5)
potion=variable(3)
pokecoins=variable(1000)
earth=variable(0)
fire=variable(0)
aqua=variable(0)
aerial=variable(0)
sector0=variable(0)
sector1=variable(0)
sector2=variable(0)
sector4=variable(0)
sector5=variable(0)
sector6=variable(0)#Sector 3,7 empty
sector8=variable(0)
sector9=variable(0)
pokeindex=variable(['pikachu'])
file1=open('pokemon.bat','wb')
pickle.dump(pikachu,file1)
pickle.dump(raichu,file1)
pickle.dump(squirtle,file1)
pickle.dump(wartortle,file1)
pickle.dump(blastoise,file1)
pickle.dump(charmender,file1)
pickle.dump(charmeleon,file1)
pickle.dump(charizard,file1)
pickle.dump(bulbasaur,file1)
pickle.dump(ivysaur,file1)
pickle.dump(venasaur,file1)
pickle.dump(pidgey,file1)
pickle.dump(pidgeotto,file1)
pickle.dump(pidgeot,file1)
pickle.dump(gastly,file1)
pickle.dump(haunter,file1)
pickle.dump(gengar,file1)
pickle.dump(abra,file1)
pickle.dump(kadabra,file1)
pickle.dump(alakazam,file1)
pickle.dump(machop,file1)
pickle.dump(machoke,file1)
pickle.dump(machamp,file1)
pickle.dump(geodude,file1)
pickle.dump(gravelar,file1)
pickle.dump(golem,file1)
pickle.dump(magmar,file1)
pickle.dump(flareon,file1)
pickle.dump(polywrath,file1)
pickle.dump(golduck,file1)
pickle.dump(taurus,file1)
pickle.dump(onix,file1)
pickle.dump(fearow,file1)
pickle.dump(farfetch,file1)
pickle.dump(dragonite,file1)
pickle.dump(zapdos,file1)
pickle.dump(vaporeon,file1)
file1.close()
file2=open('variable.bat','wb')
pickle.dump(pokeballs,file2)
pickle.dump(potion,file2)
pickle.dump(pokecoins,file2)
pickle.dump(earth,file2)
pickle.dump(fire,file2)
pickle.dump(aqua,file2)
pickle.dump(aerial,file2)
pickle.dump(sector0,file2)
pickle.dump(sector1,file2)
pickle.dump(sector2,file2)
pickle.dump(sector4,file2)
pickle.dump(sector5,file2)
pickle.dump(sector6,file2)
pickle.dump(sector8,file2)
pickle.dump(sector9,file2)
pickle.dump(pokeindex,file2)
file2.close()

